FROM openjdk:8-jre-slim
ENV JAR_FILE /oauthserver-service/oauthserver-web/target/oauthserver-web-1.0-SNAPSHOT.jar
ADD ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]